version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: meu-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Measurements
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: meu-backend-container
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: Measurements
    volumes:
      - ./backend/src:/app/src
      - ./backend/build:/app/build

volumes:
  db_data:
